import type { PageLoad } from './$types';

// Disable prerendering to allow runtime data fetching
export const prerender = false;

export const load: PageLoad = async ({ fetch }) => {
	try {
		// Fetch 8 most recent non-autogenerated artworks
		const response = await fetch('/api/artworks?autogenerated=false&limit=8');

		if (!response.ok) {
			console.error('Failed to fetch artworks:', response.statusText);
			return { artworks: [] };
		}

		const data = await response.json();
		return {
			artworks: data.artworks || []
		};
	} catch (error) {
		console.error('Error loading artworks:', error);
		return { artworks: [] };
	}
};
