<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// Cycle through Kid Pix colors for cards
	const cardColors = [
		'bg-kidpix-yellow',
		'bg-kidpix-cyan',
		'bg-kidpix-pink',
		'bg-kidpix-orange',
		'bg-white'
	];
</script>

<svelte:head>
	<title>Claude Draws - AI-Generated Kid Pix Art</title>
	<meta
		name="description"
		content="Gallery of crowdsourced illustrations created by Claude for Chrome using Kid Pix"
	/>
</svelte:head>

<div class="min-h-screen bg-gray-100">
	<!-- Header -->
	<header class="bg-kidpix-red border-b-4 border-black p-6 shadow-chunky-lg">
		<h1 class="text-5xl font-black text-white uppercase text-center tracking-wide">
			Claude Draws
		</h1>
	</header>

	<!-- Navigation/Subtitle Bar -->
	<nav class="bg-kidpix-purple border-b-4 border-black p-4">
		<p class="text-white font-bold text-xl text-center uppercase">
			AI-Generated Kid Pix Art from Reddit
		</p>
	</nav>

	<!-- Main Content -->
	<main class="container mx-auto p-4 sm:p-8">
		{#if data.artworks.length === 0}
			<div class="text-center py-12">
				<div class="inline-block bg-kidpix-yellow border-4 border-black p-8 shadow-chunky-lg">
					<p class="text-2xl font-black uppercase">No artworks yet. Check back soon!</p>
				</div>
			</div>
		{:else}
			<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
				{#each data.artworks as artwork, i}
					<a
						href="/artwork/{artwork.id}"
						class="group block {cardColors[i % cardColors.length]} border-4 border-black p-4 shadow-chunky hover:shadow-chunky-hover hover:-translate-y-1 hover:rotate-[-2deg] transition-all duration-200"
					>
						<div class="aspect-[4/3] bg-white border-2 border-black mb-3">
							<img
								src={artwork.imageUrl}
								alt={artwork.title}
								class="w-full h-full object-contain"
							/>
						</div>
						<h2 class="font-black text-lg uppercase leading-tight mb-2">
							{#if artwork.autogenerated}<span class="text-kidpix-purple">[AUTO]</span> {/if}{artwork.title}
						</h2>
						<time class="text-sm font-bold">
							{new Date(artwork.createdAt).toLocaleDateString()}
						</time>
					</a>
				{/each}
			</div>
		{/if}
	</main>

	<!-- Footer -->
	<footer class="bg-black text-white p-6 border-t-4 border-kidpix-yellow mt-12">
		<p class="text-center font-bold uppercase">Made with AI Browser Automation</p>
	</footer>
</div>
