import type { PageLoad } from './$types';

interface Artwork {
	id: string;
	title: string;
	imageUrl: string;
	image_url?: string;
	video_url?: string;
	createdAt: string;
	autogenerated?: boolean;
}

// Disable prerendering to allow runtime data fetching
export const prerender = false;

export const load: PageLoad = async ({ fetch }) => {
	try {
		// Fetch featured artwork (most recent) and recent artworks in parallel
		const [featuredResponse, recentResponse] = await Promise.all([
			fetch('/api/artworks?autogenerated=false&limit=1'),
			fetch('/api/artworks?autogenerated=false&limit=8')
		]);

		let featuredArtwork: Artwork | null = null;
		let artworks: Artwork[] = [];

		if (featuredResponse.ok) {
			const featuredData = await featuredResponse.json();
			featuredArtwork = featuredData.artworks?.[0] || null;
		} else {
			console.error('Failed to fetch featured artwork:', featuredResponse.statusText);
		}

		if (recentResponse.ok) {
			const recentData = await recentResponse.json();
			artworks = recentData.artworks || [];
		} else {
			console.error('Failed to fetch artworks:', recentResponse.statusText);
		}

		return {
			featuredArtwork,
			artworks
		};
	} catch (error) {
		console.error('Error loading artworks:', error);
		return { featuredArtwork: null, artworks: [] as Artwork[] };
	}
};
