services:
  temporal:
    image: temporalio/temporal:latest
    command: server start-dev --ip 0.0.0.0
    ports:
      - "7233:7233"  # Temporal server
      - "8233:8233"  # Temporal UI
    volumes:
      - temporal-data:/root/.config/temporalio
    healthcheck:
      test: ["CMD", "temporal", "workflow", "list", "--address", "localhost:7233"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_HOST=temporal:7233
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
    volumes:
      - .:/app
      - /app/.venv
      - /app/node_modules
      - /app/gallery/node_modules
    working_dir: /app
    command: uv run python -m worker.main

volumes:
  temporal-data:
