-- Create artworks table for storing completed Claude Draws artwork metadata
CREATE TABLE artworks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  artist_statement TEXT,
  image_url TEXT NOT NULL,
  submission_id TEXT,  -- Links to submissions table (NULL for autogenerated artworks)
  created_at TEXT NOT NULL,
  video_url TEXT,
  prompt TEXT,
  autogenerated INTEGER DEFAULT 0  -- SQLite boolean (0=false, 1=true)
);

-- Index for listing artworks (most recent first)
CREATE INDEX idx_artworks_created_at ON artworks(created_at DESC);

-- Index for filtering autogenerated artworks
CREATE INDEX idx_artworks_autogenerated ON artworks(autogenerated, created_at DESC);

-- Index for looking up by submission
CREATE INDEX idx_artworks_submission_id ON artworks(submission_id) WHERE submission_id IS NOT NULL;
