name = "claude-draws-gallery"
compatibility_date = "2025-10-12"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# D1 Database for form submissions
[[d1_databases]]
binding = "DB"
database_name = "claudedraws-prod"
database_id = "72183c83-d7e4-4d67-b18f-75599d53f330"
migrations_dir = "migrations"

# R2 Bucket for reference images and artworks
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "claudedraws-prod"

# Custom domain configuration
[[routes]]
pattern = "claudedraws.com"
custom_domain = true
