name = "claude-draws-gallery"
compatibility_date = "2025-10-12"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# D1 Database for form submissions
[[d1_databases]]
binding = "DB"
database_name = "claudedraws-dev"
database_id = "d1804ba1-e116-4139-8f5a-061e44881f0c"
migrations_dir = "migrations"

# R2 Bucket for reference images and artworks
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "claudedraws-dev"

# Custom domain configuration
[[routes]]
pattern = "claudedraws.com"
custom_domain = true
