<script lang="ts">
	import type { PageData } from './$types';
	import Header from '$lib/components/Header.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import ArtworkCard from '$lib/components/ArtworkCard.svelte';

	let { data }: { data: PageData } = $props();

	// Cycle through Kid Pix colors for cards
	const cardColors = [
		'bg-kidpix-yellow',
		'bg-kidpix-cyan',
		'bg-kidpix-pink',
		'bg-kidpix-orange',
		'bg-white'
	];

	// State for infinite scroll
	const ITEMS_PER_PAGE = 24;
	let displayedArtworks = $state(data.artworks);
	let currentOffset = $state(ITEMS_PER_PAGE);
	let totalArtworks = $state(data.pagination?.total || 0);
	let hasMore = $state(data.pagination?.hasMore || false);
	let isLoading = $state(false);
	let loadMoreTrigger = $state<HTMLDivElement | undefined>(undefined);

	// Function to load more artworks from API
	async function loadMore() {
		if (isLoading || !hasMore) return;

		isLoading = true;
		try {
			const response = await fetch(
				`/api/artworks?autogenerated=false&limit=${ITEMS_PER_PAGE}&offset=${currentOffset}`
			);

			if (response.ok) {
				const result = await response.json();
				displayedArtworks = [...displayedArtworks, ...(result.artworks || [])];
				currentOffset += ITEMS_PER_PAGE;
				hasMore = result.pagination?.hasMore || false;
				totalArtworks = result.pagination?.total || totalArtworks;
			}
		} catch (error) {
			console.error('Error loading more artworks:', error);
		} finally {
			isLoading = false;
		}
	}

	// Intersection Observer for infinite scroll
	$effect(() => {
		if (!loadMoreTrigger) return;

		const observer = new IntersectionObserver(
			(entries) => {
				if (entries[0].isIntersecting && hasMore && !isLoading) {
					loadMore();
				}
			},
			{
				rootMargin: '200px'
			}
		);

		observer.observe(loadMoreTrigger);

		return () => observer.disconnect();
	});
</script>

<svelte:head>
	<title>Gallery - Claude Draws</title>
	<meta
		name="description"
		content="Browse all AI-generated Kid Pix artworks from Claude Draws"
	/>
</svelte:head>

<div class="min-h-screen">
	<Header />

	<!-- Navigation/Back Button Bar -->
	<nav class="bg-kidpix-purple border-b-4 border-black p-4">
		<div class="container mx-auto flex justify-between items-center">
			<a
				href="/"
				class="bg-kidpix-yellow text-black font-bold text-lg px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 active:translate-x-2 active:translate-y-2 active:shadow-none uppercase transition-all"
			>
				← Back
			</a>
			<p class="text-white font-bold text-xl text-center uppercase hidden sm:block">
				Full Gallery
			</p>
		</div>
	</nav>

	<!-- Main Content -->
	<main class="container mx-auto p-4 sm:p-8">
		<!-- Stats/Intro Section -->
		<div class="bg-kidpix-yellow border-4 border-black p-6 shadow-chunky-lg mb-6">
			<p class="text-lg sm:text-xl font-bold text-center leading-relaxed">
				Claude Draws has created {totalArtworks} artwork{totalArtworks === 1 ? '' : 's'}.
			</p>
		</div>
		{#if displayedArtworks.length === 0}
			<div class="text-center py-12">
				<div class="inline-block bg-kidpix-yellow border-4 border-black p-8 shadow-chunky-lg">
					<p class="text-2xl font-black uppercase">No artworks to display.</p>
				</div>
			</div>
		{:else}
			<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
				{#each displayedArtworks as artwork, i}
					<ArtworkCard {artwork} color={cardColors[i % cardColors.length]} index={i} />
				{/each}
			</div>

			<!-- Infinite scroll trigger element -->
			{#if hasMore}
				<div bind:this={loadMoreTrigger} class="py-8 text-center">
					<div class="inline-block bg-kidpix-pink border-4 border-black p-4 shadow-chunky">
						<p class="text-lg font-black uppercase">Loading more...</p>
					</div>
				</div>
			{:else}
				<div class="py-8 text-center">
					<div class="inline-block bg-kidpix-green border-4 border-black p-4 shadow-chunky">
						<p class="text-lg font-black uppercase">You've reached the end!</p>
					</div>
				</div>
			{/if}
		{/if}
	</main>

	<Footer />
</div>
