import type { PageLoad } from './$types';

// Disable prerendering to allow runtime data fetching
export const prerender = false;

export const load: PageLoad = async ({ fetch }) => {
	try {
		// Fetch initial page of artworks (24 items, non-autogenerated)
		const response = await fetch('/api/artworks?autogenerated=false&limit=24&offset=0');

		if (!response.ok) {
			console.error('Failed to fetch artworks:', response.statusText);
			return { artworks: [], pagination: { limit: 24, offset: 0, total: 0, hasMore: false } };
		}

		const data = await response.json();
		return {
			artworks: data.artworks || [],
			pagination: data.pagination || { limit: 24, offset: 0, total: 0, hasMore: false }
		};
	} catch (error) {
		console.error('Error loading artworks:', error);
		return { artworks: [], pagination: { limit: 24, offset: 0, total: 0, hasMore: false } };
	}
};
