<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const { artwork } = data;
</script>

<svelte:head>
	<title>{artwork.title} - Claude Draws</title>
	<meta name="description" content={`${artwork.title} - AI-generated Kid Pix art`} />
	<meta property="og:title" content={artwork.title} />
	<meta property="og:description" content="AI-generated Kid Pix art" />
	<meta property="og:image" content={artwork.imageUrl} />
	<meta property="og:type" content="website" />
</svelte:head>

<div class="min-h-screen bg-gray-100">
	<!-- Header -->
	<header class="bg-kidpix-red border-b-4 border-black p-6 shadow-chunky-lg">
		<h1 class="text-5xl font-black text-white uppercase text-center tracking-wide">
			Claude Draws
		</h1>
	</header>

	<!-- Navigation/Subtitle Bar -->
	<nav class="bg-kidpix-purple border-b-4 border-black p-4">
		<div class="container mx-auto flex justify-between items-center">
			<a
				href="/"
				class="bg-kidpix-yellow text-black font-bold text-lg px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 active:translate-x-2 active:translate-y-2 active:shadow-none uppercase transition-all"
			>
				← Back
			</a>
			<p class="text-white font-bold text-xl text-center uppercase hidden sm:block">
				Artwork Details
			</p>
		</div>
	</nav>

	<!-- Main Content -->
	<main class="container mx-auto p-4 sm:p-8">
		<div class="max-w-4xl mx-auto bg-kidpix-cyan border-4 border-black shadow-chunky-lg">
			<!-- Image Container -->
			<div class="bg-white border-b-4 border-black p-4 sm:p-8">
				<div class="border-4 border-black bg-gray-100 p-2">
					<img
						src={artwork.imageUrl}
						alt={artwork.title}
						class="w-full h-auto mx-auto"
					/>
				</div>
			</div>

			<!-- Content Container -->
			<div class="p-4 sm:p-8">
				<!-- Title -->
				<div class="bg-kidpix-yellow border-4 border-black p-4 shadow-chunky mb-6">
					<h1 class="text-2xl sm:text-3xl font-black uppercase leading-tight">
						{#if artwork.autogenerated}<span class="text-kidpix-purple">[AUTO]</span> {/if}{artwork.title}
					</h1>
				</div>

				<!-- Artist Statement -->
				{#if artwork.artistStatement}
					<div class="bg-white border-4 border-black p-4 sm:p-6 shadow-chunky mb-6">
						<h2 class="text-xl font-black uppercase mb-3 pb-2 border-b-4 border-black">
							Artist Statement
						</h2>
						<div class="text-base sm:text-lg font-bold whitespace-pre-wrap leading-relaxed">
							{artwork.artistStatement}
						</div>
					</div>
				{/if}

				<!-- Metadata Grid -->
				<div class="space-y-4">
					<!-- Created Date -->
					<div class="bg-kidpix-pink border-4 border-black p-4 shadow-chunky">
						<h2 class="text-lg font-black uppercase mb-2">Created</h2>
						<time class="text-base font-bold">
							{new Date(artwork.createdAt).toLocaleString('en-US', {
								dateStyle: 'full',
								timeStyle: 'short'
							})}
						</time>
					</div>

					<!-- Inspired By -->
					<div class="bg-kidpix-orange border-4 border-black p-4 shadow-chunky">
						<h2 class="text-lg font-black uppercase mb-2">Inspired By</h2>
						{#if artwork.redditPostUrl}
							<a
								href={artwork.redditPostUrl}
								target="_blank"
								rel="noopener noreferrer"
								class="inline-block bg-kidpix-blue text-white font-bold text-base px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 uppercase transition-all"
							>
								View Reddit Post →
							</a>
						{:else}
							<p class="text-base font-bold">An original creation from Claude Draws</p>
						{/if}
					</div>

					<!-- Original Prompt -->
					{#if artwork.prompt}
						<div class="bg-kidpix-green border-4 border-black p-4 shadow-chunky">
							<details class="group">
								<summary class="text-lg font-black uppercase cursor-pointer hover:text-black list-none flex items-center gap-2">
									<span class="transform transition-transform group-open:rotate-90 text-2xl">▶</span>
									Original Prompt
								</summary>
								<div class="mt-4 text-sm bg-white p-4 border-4 border-black whitespace-pre-wrap font-mono leading-relaxed max-h-96 overflow-y-auto">
									{artwork.prompt}
								</div>
							</details>
						</div>
					{/if}

					<!-- Video Link -->
					{#if artwork.videoUrl}
						<div class="bg-kidpix-purple border-4 border-black p-4 shadow-chunky">
							<h2 class="text-lg font-black uppercase mb-2 text-white">
								Creation Process
							</h2>
							<a
								href={artwork.videoUrl}
								target="_blank"
								rel="noopener noreferrer"
								class="inline-block bg-kidpix-red text-white font-bold text-base px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 uppercase transition-all"
							>
								Watch Video →
							</a>
						</div>
					{/if}
				</div>

				<!-- Footer Note -->
				<div class="mt-8 bg-black text-white border-4 border-kidpix-yellow p-4 shadow-chunky">
					<p class="text-sm font-bold uppercase text-center">
						Created by Claude for Chrome using Kid Pix
					</p>
				</div>
			</div>
		</div>
	</main>

	<!-- Footer -->
	<footer class="bg-black text-white p-6 border-t-4 border-kidpix-yellow mt-12">
		<p class="text-center font-bold uppercase">Made with AI Browser Automation</p>
	</footer>
</div>
