<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const { artwork } = data;
</script>

<svelte:head>
	<title>{artwork.title} - Claude Draws</title>
	<meta name="description" content={`${artwork.title} - AI-generated Kid Pix art`} />
	<meta property="og:title" content={artwork.title} />
	<meta property="og:description" content="AI-generated Kid Pix art" />
	<meta property="og:image" content={artwork.imageUrl} />
	<meta property="og:type" content="website" />
</svelte:head>

<div class="container mx-auto px-4 py-8">
	<div class="mb-6">
		<a href="/" class="text-blue-600 hover:text-blue-800 transition-colors">
			← Back to Gallery
		</a>
	</div>

	<div class="max-w-4xl mx-auto bg-white rounded-lg shadow-lg overflow-hidden">
		<div class="bg-gray-100 p-8">
			<img
				src={artwork.imageUrl}
				alt={artwork.title}
				class="w-full h-auto pixelated mx-auto"
			/>
		</div>

		<div class="p-8">
			<h1 class="text-3xl font-bold mb-4">
				{#if artwork.autogenerated}<span class="text-purple-600">[Auto]</span> {/if}{artwork.title}
			</h1>

			{#if artwork.artistStatement}
				<div class="mb-6 text-gray-700 text-lg whitespace-pre-wrap leading-relaxed">
					{artwork.artistStatement}
				</div>
			{/if}

			<div class="space-y-4 text-gray-700">
				<div>
					<h2 class="text-sm font-semibold text-gray-500 uppercase mb-1">Created</h2>
					<time class="text-lg">
						{new Date(artwork.createdAt).toLocaleString('en-US', {
							dateStyle: 'full',
							timeStyle: 'short'
						})}
					</time>
				</div>

				<div>
					<h2 class="text-sm font-semibold text-gray-500 uppercase mb-1">Inspired By</h2>
					{#if artwork.redditPostUrl}
						<a
							href={artwork.redditPostUrl}
							target="_blank"
							rel="noopener noreferrer"
							class="text-lg text-blue-600 hover:text-blue-800 transition-colors"
						>
							View Reddit Post →
						</a>
					{:else}
						<p class="text-lg text-gray-600">An original creation from Claude Draws</p>
					{/if}
				</div>

				{#if artwork.prompt}
					<div>
						<details class="group">
							<summary class="text-sm font-semibold text-gray-500 uppercase cursor-pointer hover:text-gray-700 transition-colors list-none flex items-center gap-2">
								<span class="transform transition-transform group-open:rotate-90">▶</span>
								Original Prompt
							</summary>
							<div class="mt-2 text-sm bg-gray-50 p-4 rounded-lg border border-gray-200 whitespace-pre-wrap font-mono leading-relaxed max-h-96 overflow-y-auto">
								{artwork.prompt}
							</div>
						</details>
					</div>
				{/if}

				{#if artwork.videoUrl}
					<div>
						<h2 class="text-sm font-semibold text-gray-500 uppercase mb-1">
							Creation Process
						</h2>
						<a
							href={artwork.videoUrl}
							target="_blank"
							rel="noopener noreferrer"
							class="text-lg text-blue-600 hover:text-blue-800 transition-colors"
						>
							Watch Video →
						</a>
					</div>
				{/if}
			</div>

			<div class="mt-8 pt-8 border-t border-gray-200">
				<p class="text-sm text-gray-600">
					This artwork was created by Claude for Chrome using Kid Pix.
				</p>
			</div>
		</div>
	</div>
</div>
