<script lang="ts">
	import type { PageData } from './$types';
	import Header from '$lib/components/Header.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import TabContainer from '$lib/components/TabContainer.svelte';
	import VideoPlayer from '$lib/components/VideoPlayer.svelte';
	import { copyToClipboard, getCanonicalUrl } from '$lib/utils/clipboard';

	let { data }: { data: PageData } = $props();
	const { artwork } = data;

	// State for copy feedback
	let showCopyFeedback = $state(false);

	// Handle permalink copy
	async function handleCopyPermalink() {
		const url = getCanonicalUrl();
		const success = await copyToClipboard(url);

		if (success) {
			showCopyFeedback = true;
			setTimeout(() => {
				showCopyFeedback = false;
			}, 2000);
		}
	}

	// Handle download
	async function handleDownload() {
		try {
			// Fetch the image as a blob to bypass CORS restrictions
			const response = await fetch(artwork.imageUrl);
			const blob = await response.blob();

			// Create a temporary object URL
			const blobUrl = URL.createObjectURL(blob);

			// Create and trigger download link
			const link = document.createElement('a');
			link.href = blobUrl;
			link.download = `${artwork.id}.png`;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);

			// Clean up the object URL
			URL.revokeObjectURL(blobUrl);
		} catch (error) {
			console.error('Download failed:', error);
			// Fallback: open image in new tab
			window.open(artwork.imageUrl, '_blank');
		}
	}

	// Handle back navigation
	function handleBack() {
		if (typeof window !== 'undefined' && window.history.length > 1) {
			window.history.back();
		} else {
			// Fallback to home page if no history
			window.location.href = '/';
		}
	}
</script>

<svelte:head>
	<title>{artwork.title} - Claude Draws</title>
	<meta name="description" content={`${artwork.title} - AI-generated Kid Pix art`} />
	<meta property="og:title" content={artwork.title} />
	<meta property="og:description" content="AI-generated Kid Pix art" />
	<meta property="og:image" content={artwork.imageUrl} />
	<meta property="og:type" content="website" />
</svelte:head>

<div class="min-h-screen">
	<Header />

	<!-- Navigation/Subtitle Bar -->
	<nav class="bg-kidpix-purple border-b-4 border-black p-4">
		<div class="container mx-auto flex justify-between items-center">
			<button
				onclick={handleBack}
				class="bg-kidpix-yellow text-black font-bold text-lg px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 active:translate-x-2 active:translate-y-2 active:shadow-none uppercase transition-all"
			>
				← Back
			</button>
			<p class="text-white font-bold text-xl text-center uppercase hidden sm:block">
				Artwork Details
			</p>
		</div>
	</nav>

	<!-- Main Content -->
	<main class="container mx-auto p-4 sm:p-8">
		<div class="max-w-4xl mx-auto bg-kidpix-cyan border-4 border-black shadow-chunky-lg">
			<!-- Tabbed Media Container -->
			<div class="bg-white border-b-4 border-black p-4 sm:p-8">
				<TabContainer hasVideo={!!artwork.videoUrl}>
					{#snippet children()}
						<div class="border-4 border-black bg-gray-100">
							<img
								src={artwork.imageUrl}
								alt={artwork.title}
								class="w-full h-auto mx-auto"
							/>
						</div>
					{/snippet}

					{#snippet videoContent()}
						{#if artwork.videoUrl}
							<VideoPlayer videoUrl={artwork.videoUrl} />
						{/if}
					{/snippet}
				</TabContainer>
			</div>

			<!-- Content Container -->
			<div class="p-4 sm:p-8">
				<!-- Action Buttons -->
				<div class="flex flex-wrap gap-3 mb-6">
					<button
						onclick={handleCopyPermalink}
						class="relative bg-kidpix-purple text-white font-bold text-base px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 active:translate-x-2 active:translate-y-2 active:shadow-none uppercase transition-all"
					>
						Permalink
						{#if showCopyFeedback}
							<span
								class="absolute -top-12 left-1/2 -translate-x-1/2 bg-kidpix-green text-black px-3 py-1 border-4 border-black font-bold text-sm whitespace-nowrap shadow-chunky"
							>
								Link copied!
							</span>
						{/if}
					</button>
					<button
						onclick={handleDownload}
						class="bg-kidpix-orange text-black font-bold text-base px-4 py-2 border-4 border-black shadow-chunky hover:shadow-chunky-hover hover:translate-x-1 hover:translate-y-1 active:translate-x-2 active:translate-y-2 active:shadow-none uppercase transition-all"
					>
						Download
					</button>
				</div>

				<!-- Title -->
				<div class="bg-kidpix-yellow border-4 border-black p-4 shadow-chunky mb-6">
					<h1 class="text-2xl sm:text-3xl font-black uppercase leading-tight">
						{#if artwork.autogenerated}<span class="text-kidpix-purple">[AUTO]</span>{' '}{/if}{artwork.title}
					</h1>
				</div>

				<!-- Artist Statement -->
				{#if artwork.artistStatement}
					<div class="bg-white border-4 border-black p-4 sm:p-6 shadow-chunky mb-6">
						<h2 class="text-xl font-black uppercase mb-3 pb-2 border-b-4 border-black">
							Artist Statement
						</h2>
						<div class="text-base sm:text-lg font-bold whitespace-pre-wrap leading-relaxed">
							{artwork.artistStatement}
						</div>
					</div>
				{/if}

				<!-- Metadata Grid -->
				<div class="space-y-4">
					<!-- Created Date -->
					<div class="bg-kidpix-pink border-4 border-black p-4 shadow-chunky">
						<h2 class="text-lg font-black uppercase mb-2">Created</h2>
						<time class="text-base font-bold">
							{new Date(artwork.createdAt).toLocaleString('en-US', {
								dateStyle: 'full',
								timeStyle: 'short'
							})}
						</time>
					</div>

					<!-- Original Prompt -->
					{#if artwork.prompt}
						<div class="bg-kidpix-green border-4 border-black p-4 shadow-chunky">
							<details class="group">
								<summary class="text-lg font-black uppercase cursor-pointer hover:text-black list-none flex items-center gap-2">
									<span class="transform transition-transform group-open:rotate-90 text-2xl">▶</span>
									Original Prompt
								</summary>
								<div class="mt-4 text-sm bg-white p-4 border-4 border-black whitespace-pre-wrap font-mono leading-relaxed max-h-96 overflow-y-auto">
									{artwork.prompt}
								</div>
							</details>
						</div>
					{/if}
				</div>

				<!-- Footer Note -->
				<div class="mt-8 bg-black text-white border-4 border-kidpix-yellow p-4 shadow-chunky">
					<p class="text-sm font-bold uppercase text-center">
						Created by Claude for Chrome using Kid Pix
					</p>
				</div>
			</div>
		</div>
	</main>

	<Footer />
</div>
