<script lang="ts">
	interface Props {
		artwork: {
			id: string;
			title: string;
			imageUrl: string;
			createdAt: string;
			autogenerated?: boolean;
		};
		color: string;
		index?: number;
	}

	let { artwork, color, index = 0 }: Props = $props();
</script>

<a
	href="/artwork/{artwork.id}"
	class="group block {color} border-4 border-black p-4 shadow-chunky hover:shadow-chunky-hover hover:-translate-y-1 hover:rotate-[-2deg] transition-all duration-200"
>
	<div class="aspect-[4/3] bg-white border-2 border-black mb-3">
		<img src={artwork.imageUrl} alt={artwork.title} class="w-full h-full object-contain" />
	</div>
	<h2 class="font-black text-lg uppercase leading-tight mb-2">
		{#if artwork.autogenerated}<span class="text-kidpix-purple">[AUTO]</span>{' '}{/if}{artwork.title}
	</h2>
	<time class="text-sm font-bold">
		{new Date(artwork.createdAt).toLocaleDateString(undefined, {
			dateStyle: 'short'
		})}
		{new Date(artwork.createdAt).toLocaleTimeString(undefined, {
			timeStyle: 'short'
		})}
	</time>
</a>
